<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    Phoenix_BankPayment
 * @copyright  Copyright (c) 2008-2009 Andrej Sinicyn, Mik3e
 * @copyright  Copyright (c) 2010-2016 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @copyright  Copyright (c) 2017-2018 Phoenix Media GmbH & Co. KG (http://www.phoenix-media.eu)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author     Achim Rosenhagen <a.rosenhagen@ffuenf.de>
 * @copyright  Copyright (c) 2015 ffuenf (http://www.ffuenf.de)
 * @license    http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<?php
    $_helper = Mage::helper('bankpayment');
    $quoteCurrencyCode = $this->getQuoteCurrencyCode();
?>
<fieldset class="form-list">
<ul id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display:none">
    <li>
        <?php if ($_cmsPage = $this->getFormCmsUrl()): ?>
            <div class="input-box">
                <p><?php echo $this->__('More information on this payment method can be found <a target="_blank" href="%s">here</a>.', $_cmsPage) ?></p>
            </div>
        <?php elseif ($_accounts = $this->getAccounts()): ?>
            <?php if (count($_accounts) == 1): ?>
                <?php if ($this->getMethod()->getPayWithinXDays() > 0): ?>
                    <?php echo $this->__('Please transfer the money within %s days to the following bank account', $this->getMethod()->getPayWithinXDays()); ?>:
                <?php else: ?>
                    <?php echo $this->__('Please transfer the money to the following bank account'); ?>:
                <?php endif; ?>
            <?php else: ?>
                <?php if ($this->getMethod()->getPayWithinXDays() > 0): ?>
                    <?php echo $this->__('Please transfer the money within %s days to one of the following bank accounts', $this->getMethod()->getPayWithinXDays()); ?>:
                <?php else: ?>
                    <?php echo $this->__('Please transfer the money to one of the following bank accounts'); ?>:
                <?php endif; ?>
            <?php endif; ?>
            <br /><br />
            <div class="input-box">
                <?php $first = true; ?>
                <?php foreach ($_accounts as $_account): ?>
                    <?php if ($_helper->displayAccountData($_account, $quoteCurrencyCode)): ?>
                        <?php if (!$first): ?>
                        <br /><hr/><br />
                        <?php endif; $first = false; ?>
                        <table>
                            <tbody>
                                <?php if ($_accountHolder = $_account->getAccountHolder()): ?>
                                    <tr><td><label><?php echo $this->__('Account holder') ?></label>: </td><td><?php echo $_accountHolder ?></td></tr>
                                <?php endif; ?>
                                <?php if ($_bankName = $_account->getBankName()): ?>
                                    <tr><td><label><?php echo $this->__('Bank name') ?></label>: </td><td><?php echo $_bankName ?></td></tr>
                                <?php endif; ?>
                                <?php if ($_helper->displaySepaAccountData($_account)): ?>
                                    <?php if ($_helper->displayNonSepaAccountData($_account)): ?>
                                        // Display only if both types of Account Data are in use
                                        <tr><td colspan="2"><br /><strong><?php echo $this->__('For international transfers please use the following data'); ?></strong></td></tr>
                                    <?php endif; ?>
                                    <tr><td><label><?php echo $this->__('IBAN') ?></label>: </td><td><?php echo $_account->getIban() ?></td></tr>
                                    <tr><td><label><?php echo $this->__('BIC') ?></label>: </td><td><?php echo $_account->getBic() ?></td></tr>
                                <?php endif; ?>
                                <?php if ($_helper->displayNonSepaAccountData($_account)): ?>
                                    <?php if ($_helper->displaySepaAccountData($_account)): ?>
                                        // Display only if both types of Account Data are in use
                                        <tr><td colspan="2"><br /><strong><?php echo $this->__('For non SEPA countries please use the following data'); ?></strong></td></tr>
                                    <?php endif; ?>
                                    <tr><td><label><?php echo $this->__('Account number') ?></label>: </td><td><?php echo $_account->getAccountNumber() ?></td></tr>
                                    <tr><td><label><?php echo $this->__('Sort code') ?></label>: </td><td><?php echo $_account->getSortCode() ?></td></tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($this->getMethod()->getCustomText()): ?>
                    <br />
                    <?php echo $this->getMethod()->getCustomText() ?><br />
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </li>
</ul>
</fieldset>
