<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    Phoenix_BankPayment
 * @copyright  Copyright (c) 2008 Andrej Sinicyn
 * @copyright  Copyright (c) 2010 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<ul id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display:none">
    <li>
    <?php if ($_cmsPage = $this->getFormCmsUrl()): ?>
        <div class="input-box">
            <p><?php echo $this->__('More information on this payment method can be found <a target="_blank" href="%s">here</a>.', $_cmsPage) ?></p>
        </div>
    <?php elseif ($_accounts = $this->getAccounts()): ?>
        <?php if (count($_accounts) == 1): ?>
            <?php if ($this->getMethod()->getPayWithinXDays() > 0): ?>
                <?php echo $this->__('Please transfer the money within %s days to the following bank account', $this->getMethod()->getPayWithinXDays()); ?>:
            <?php else: ?>
                <?php echo $this->__('Please transfer the money to the following bank account'); ?>:
            <?php endif; ?>
        <?php else: ?>
            <?php if ($this->getMethod()->getPayWithinXDays() > 0): ?>
                <?php echo $this->__('Please transfer the money within %s days to one of the following bank accounts', $this->getMethod()->getPayWithinXDays()); ?>:
            <?php else: ?>
                <?php echo $this->__('Please transfer the money to one of the following bank accounts'); ?>:
            <?php endif; ?>
        <?php endif; ?>
        <br /><br />
        <div class="input-box">
            <?php $first = true; ?>
            <?php foreach($_accounts as $_account): ?>
                <?php if (!$first): ?>
                <br /><hr/><br />
                <?php endif; $first = false; ?>
            <table>
                <tbody>
                    <?php if ($_accountHolder = $_account->getAccountHolder()): ?>
                        <tr><td><label><?php echo $this->__('Account holder') ?>:</label> </td><td><?php echo $_accountHolder ?></td></tr>
                    <?php endif; ?>
                    <!--
                    <?php if ($_accountNumber = $_account->getAccountNumber()): ?>
                        <tr><td><label><?php echo $this->__('Account number') ?>:</label> </td><td><?php echo $_accountNumber ?></td></tr>
                    <?php endif; ?>
                    <?php if ($_sortCode = $_account->getSortCode()): ?>
                        <tr><td><label><?php echo $this->__('Sort code') ?>:</label> </td><td><?php echo $_sortCode ?></td></tr>
                    <?php endif; ?>
                    -->
                    <?php if ($_bankName = $_account->getBankName()): ?>
                        <tr><td><label><?php echo $this->__('Bank name') ?>:</label> </td><td><?php echo $_bankName ?></td></tr>
                    <?php endif; ?>
                </tbody>
            </table>
            <!--
            <?php if (($_iban = $_account->getIban()) && ($_bic = $_account->getBic())): ?>
                <p><?php echo $this->__('For international transfers please use the following data') ?>:</p>
                <table>
                    <tbody>
                        <tr><td><label><?php echo $this->__('IBAN') ?>:</label> </td><td><?php echo $_iban ?></td></tr>
                        <tr><td><label><?php echo $this->__('BIC') ?>:</label> </td><td><?php echo $_bic ?></td></tr>
                    </tbody>
                </table>
            <?php endif; ?>
            -->
            <?php endforeach; ?>
            <!--
            <?php if ($_customText = $this->getMethod()->getCustomText()): ?>
                <br />
                <?php echo $_customText ?><br />
            <?php endif; ?>
             -->
        </div>
    <?php endif; ?>
    </li>
</ul>
