<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    Phoenix_BankPayment
 * @copyright  Copyright (c) 2008 Andrej Sinicyn
 * @copyright  Copyright (c) 2010 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<p>
    <?php echo $this->getMethod()->getTitle(); ?> - <span style="font-style:italic;"><?php echo $this->__('Account info'); ?></span><br />
    <?php $_accounts = $this->getAccounts(); ?>
    <?php foreach($_accounts as $_account): ?>
    <br />
    <table class="bankpayment_info">
        <tbody>
        <?php if ($_accountHolder = $_account->getAccountHolder()): ?>
            <tr>
                <td class="bankcol1"><label><?php echo $this->__('Account holder') ?>:</label> </td>
                <td class="bankcol2"><?php echo $_accountHolder ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($_bankName = $_account->getBankName()): ?>
            <tr>
                <td class="bankcol1"><label><?php echo $this->__('Bank name') ?>:</label> </td>
                <td class="bankcol2"><?php echo $_bankName ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($_bankName = $_account->getIban()): ?>
            <tr>
                <td class="bankcol1"><label><?php echo $this->__('IBAN') ?>:</label> </td>
                <td class="bankcol2"><?php echo $_iban ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($_bankName = $_account->getBic()): ?>
            <tr>
                <td class="bankcol1"><label><?php echo $this->__('BIC') ?>:</label> </td>
                <td class="bankcol2"><?php echo $_bic ?></td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
    <?php endforeach; ?>
    <?php if ($_customText = $this->getMethod()->getCustomText()): ?>
        <br />
        <?php echo $_customText; ?><br />
    <?php endif; ?>
</p>
