<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    Phoenix_BankPayment
 * @copyright  Copyright (c) 2008-2009 Andrej Sinicyn, Mik3e
 * @copyright  Copyright (c) 2010-2016 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @copyright  Copyright (c) 2017-2018 Phoenix Media GmbH & Co. KG (http://www.phoenix-media.eu)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author     Achim Rosenhagen <a.rosenhagen@ffuenf.de>
 * @copyright  Copyright (c) 2015 ffuenf (http://www.ffuenf.de)
 * @license    http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<?php
    $_helper = Mage::helper('bankpayment');
    $quoteCurrencyCode = $this->getQuoteCurrencyCode();
?>
<?php if ($_info = $this->getInfo()): ?>
    <?php echo $this->getMethod()->getTitle(); ?>
    <?php if ($this->getShowBankAccountsInPdf()): ?>
        <?php echo ' - '.$this->__('Account info'); ?>
        {{pdf_row_separator}}
        <?php $_accounts = $this->getAccounts(); ?>
        <?php foreach ($_accounts as $_account): ?>
            <?php if ($_helper->displayAccountData($_account, $quoteCurrencyCode)): ?>
                {{pdf_row_separator}}
                <?php if ($_accountHolder = $_account->getAccountHolder()): ?>
                    <?php echo $this->__('Account holder') ?>: <?php echo $_accountHolder ?>
                    {{pdf_row_separator}}
                <?php endif; ?>
                <?php if ($_bankName = $_account->getBankName()): ?>
                    <?php echo $this->__('Bank name') ?>: <?php echo $_bankName ?>
                    {{pdf_row_separator}}
                <?php endif; ?>
                <?php if ($_helper->displaySepaAccountData($_account)): ?>
                    <?php if ($_helper->displayNonSepaAccountData($_account)): ?>
                        {{pdf_row_separator}}
                        --- <?php echo $this->__('Account data for SEPA countries'); ?> ---
                    <?php endif; ?>
                    {{pdf_row_separator}}
                    <?php echo $this->__('IBAN') ?>: <?php echo $_account->getIban() ?>
                    {{pdf_row_separator}}
                    <?php echo $this->__('BIC') ?>: <?php echo $_account->getBic() ?>
                    {{pdf_row_separator}}
                <?php endif; ?>
                <?php if ($_helper->displayNonSepaAccountData($_account)): ?>
                    <?php if ($_helper->displaySepaAccountData($_account)): ?>
                        {{pdf_row_separator}}
                        --- <?php echo $this->__('Account data for non SEPA countries'); ?> ---
                    <?php endif; ?>
                    {{pdf_row_separator}}
                    <?php echo $this->__('Account number') ?>: <?php echo $_account->getAccountNumber() ?>
                    {{pdf_row_separator}}
                    <?php echo $this->__('Sort code') ?>: <?php echo $_account->getSortCode() ?>
                    {{pdf_row_separator}}
                <?php endif; ?>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
    <?php if ($this->getShowCustomTextInPdf() && $_customText = $this->getMethod()->getCustomText()): ?>
        {{pdf_row_separator}}
        <?php echo $_customText; ?>
    <?php endif; ?>
    {{pdf_row_separator}}
<?php endif; ?>
