<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    Phoenix_BankPayment
 * @copyright  Copyright (c) 2010-2016 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @copyright  Copyright (c) 2017-2018 Phoenix Media GmbH & Co. KG (http://www.phoenix-media.eu)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$_order = $this->getOrder();
$_countryId = $_order->getShippingAddress()->getData('country_id');
?>
<?php if (strcmp($_order->getPayment()->getMethod(), 'bankpayment') == 0): ?>
    <p style="font-weight:bold;color:#ff0004"><?php echo $this->__('***IMPORTANT***'); ?><br />
    <?php echo $this->__('Please use the following reference on your bank transfer:'); ?></p>
    <pre><?php echo $_order->increment_id ?></pre>
    <?php if ($_countryId == 'CH'): ?>
        <p style="font-weight:bold;color:#ff0004"><?php echo $this->__('Please be aware of any applicable fees of your bank for international transfers!') ?></p>
    <?php endif; ?>
<?php endif; ?>